Feat/follow
Bansuk/projeto_11_linkr pull request #18
Opened 2021-09-22 17:01 UTC by jefranca

Seguir e deixar de seguir um usuario

- Ao entrar na pagina, o botao aparece como "Carregando...", logo apos carregar, caso já siga o usuario, o botão mudará para "Unfollow", caso contrario para "Follow"
- Ao clicar no botão o mesmo voltara para "Carregando..." até concluir o post
- caso encontre um erro, aparecera uma alerta e o botão voltará para posiçao anterior, exemplo se deu falha para seguir o usuario o alerta será "Não Foi possível seguir o usuário" e o botão voltará para Follow.
- caso contrario ira seguir ou deixar de seguir o usuario, e o botão mudará de "Follow" para "Unfollow" ou de "Follow" para "Unfollow"

2021-09-22 17:50 UTC, Bansuk commented
Tudo parece estar funcionando corretamente. Eu só sugeriria alterar o cursor para pointer quando o usuário der hover em cima do botão de follow/unfollow

2021-09-22 17:51 UTC, Bansuk commented
Tudo parece estar funcionando corretamente. Eu só sugeriria alterar o cursor para pointer quando o usuário der hover em cima do botão de follow/unfollow

2021-09-22 18:12 UTC, Paulo-Piotto commented
E tbm acho interessante diminuir um pouco o tamanho da fonte, pra ficar mais próximo do modelo no layout do figma, de resto parece tudo ok

2021-09-23 06:15 UTC, sidneyouteiro requested changes
Nomes muito grandes acabam quebrando o layout, acredito que esse [link](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) possa ajudar. E um conselho seria separar o componente `Heading` do botão follow encapsulando ambos com div's e delimitando a área do texto e imagem do heading de tal forma que não 'esmague' o botão de follow/unfollow 
![image](https://user-images.githubusercontent.com/44553251/134461573-4077a8f2-f777-4dd9-9253-9c26163823b6.png)

2021-09-23 06:15 UTC, sidneyouteiro commented on src/components/myLikes.js
> +                )}
O estado inicial é de myPosts é um array, e o valor booleano (ou valor verdade) de um array é sempre true mesmo que ele esteja vazio. Uma alternativa é usar `myPostsList.lenght`no lugar de `myPostsList && myPostsList[0]` para avaliar se um array está vazio ou não.

OBS: `array.lenght ? /*array não está vazio*/ : /*array está vazio*/`

2021-09-23 06:15 UTC, sidneyouteiro commented on src/components/usersPosts.js
> +                        </div>
trocar `myPostsList && myPostsList[0]` por `myPostsList.lenght`

2021-09-25 07:39 UTC, sidneyouteiro commented
Basta resolver os conflitos que eu irei aprovar

2021-09-25 14:59 UTC, sidneyouteiro approved these changes

2021-09-25 14:59 UTC, merged