Feat/repost
Bansuk/projeto_11_linkr pull request #22
Opened 2021-09-23 01:09 UTC by Bansuk

- Inclusão do botão de repost embaixo do botão de like,
- Componetização do modal para que o mesmo possa ser utilizado tanto para exclusão de post, quanto para confirmação de repost,
- Novo layout para indicar o último usuário a ter dado repost, caso haja.

2021-09-23 18:39 UTC, Paulo-Piotto commented
Bruno, pra mim no post original tbm ta ficando com o layout como se fosse repost, ai fica um "reposted by" mas sem nenhum nome na frente, esse é o comportamento que deve ter msm?

2021-09-23 18:43 UTC, Paulo-Piotto approved these changes

2021-09-23 18:54 UTC, jefranca commented
O modal ta com a mesma linha em volta que estava o modal de deletar o post, e eu colocaria um onrequestclose no modal para quando clicar fora do modal ele fechar também mas acho que isso é opcional

2021-09-23 18:55 UTC, jefranca approved these changes

2021-09-25 06:59 UTC, sidneyouteiro requested changes

2021-09-25 06:59 UTC, sidneyouteiro commented on src/components/ConfirmationModal.js
> +                                : "Yes, share!"}
Acredito que seja manter os textos com um único idioma

2021-09-25 06:59 UTC, sidneyouteiro commented on src/components/Timeline.js
> +                            }
Poderíamos transformar da linha 47~53 em uma função assim para deixarmos os componentes mais enxutos.

2021-09-25 06:59 UTC, sidneyouteiro commented on src/components/Post.js
> +                                }
Ternários encadeados podem dificultar a leitura do código e usa-los em casos que não tenha um "`else`" não são apropriados 
```
onKeyDown={e => {
     if(e.key === "Escape") setIsEditing(false)
     if(e.key === "Enter") saveModification(e)
}}
```

2021-09-25 06:59 UTC, sidneyouteiro commented on src/components/Post.js
> +                                        : repostCount - 1}{" "}
Considerando que não poderá ter inconsistências vindas do servidor, podemos colocar dessar forma
```
{repostCount && !repostUserId ? repostCount - 1 : repostCount }

```
Avaliando o caso mais específico e complicado primeiro (`repostCount -1`) eu consigo deixar mais simples a verificação tanto para ler quando para entender e as demais possibilidades ou levarão para `repostCount` ou serão impossíveis, pois seriam inconsistências do servidor

2021-09-25 12:29 UTC, Bansuk commented on src/components/Post.js
> +                                        : repostCount - 1}{" "}
Bem mais simples mesmo, tive dificuldade em estruturar isso. Obrigado pela orientação!

2021-09-25 17:46 UTC, sidneyouteiro commented
Basta resolver os conflitos e será aprovado 👍🏽

2021-09-26 14:33 UTC, sidneyouteiro approved these changes

2021-09-26 14:33 UTC, merged