Feat/comments
Bansuk/projeto_11_linkr pull request #26
Opened 2021-09-24 18:47 UTC by Bansuk

- Ao clicar nos comentários de um post, deve abrir abaixo a caixa de comentários
- Ao submeter um comentário, este deve ser adicionado na lista de comentários do post
- Ao lado do nome dos autores dos comentários deve aparecer "post's author" quando a pessoa é autora do post
- Ao lado do nome dos autores dos comentários deve aparecer "following" caso você siga aquela pessoa

2021-09-24 19:14 UTC, Paulo-Piotto reviewed
Boa Bruno, layout ficou muito bom, eu acho que só poderia ter duas alterações qnd fizer o post do comentario acho que seria legal retirar o texto do input e ja atualizar os comentários, pq qnd eu faço um comentário ele só tá aparecendo qnd eu fecho e abro os comentários de novo

2021-09-24 19:23 UTC, jefranca approved these changes
Concordo com o Paulo, e eu colocaria um padding no placeholder para nao começar digitando ja na borda, dar um espaço

2021-09-25 07:35 UTC, sidneyouteiro requested changes

2021-09-25 07:35 UTC, sidneyouteiro commented on src/components/Comment.js
> +                                : ""}
Poderíamos transformar esse trecho em uma função para tornar mais legível
```
function authorAdditionalInfo(){
    if(id === authorId) return " • posts's author";

    const numberFollowers = following.filter(e => e.id === id).length;
    if(numberFollowers) return " • following";
}
```

2021-09-25 07:35 UTC, sidneyouteiro commented on src/components/CommentInput.js
> +                    value={isDisabled ? "" : comment}
```
placeholder={!isDisabled && "write a comment..."}
value={!isDisabled && comment}
```

2021-09-25 07:35 UTC, sidneyouteiro commented on src/components/CommentInput.js
> +                    onKeyDown={e => (e.key === "Enter" ? saveComment() : "")}
`onKeyDown={e => if(e.key === "Enter")  saveComment()}`

2021-09-25 07:35 UTC, sidneyouteiro commented on src/components/ConfirmationModal.js
> +                                : "Yes, share!"}
Acredito que seja ideal manter um mesmo idioma nas strings que serão apresentadas para o usuário

2021-09-25 07:35 UTC, sidneyouteiro commented on src/components/Post.js
> +            )}
✅ `{repostCount && (...) }`  
❌ `{repostCount ? (...) : ""}`

2021-09-25 15:12 UTC, sidneyouteiro commented
Basta resolver os conflitos e irei aprovar

2021-09-25 21:11 UTC, sidneyouteiro requested changes
Eu notei enquanto testava novamente que a caixa de comentários trunca comentários muito grandes ou uma palavra que seja muito grande. Exemplo:
![image](https://user-images.githubusercontent.com/44553251/134786094-347da756-7f79-4a2b-b44d-538c861abb98.png)

Acredito que esse link [aqui](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) possa ajudar a quebrar palavras muito grandes

2021-09-25 21:11 UTC, sidneyouteiro commented on src/components/Post.js
> +            )}
```
            {showComments
                && comments.map(comment => (
                      <Comment
                          key={comment.id}
                          comment={comment}
                          authorId={userId}
                          token={token}
                      />
                  ))}
            {showComments && (
                <CommentInput
                    token={token}
                    postId={id}
                    avatar={user.avatar}
                    getComments={getComments}
                />
            )}
```

2021-09-25 21:11 UTC, sidneyouteiro commented on src/components/Post.js
> +                            )}
```
                            {user.id === userId && (
                                <div>
                                    <TiPencil
                                        className={"post__edit-button"}
                                        onClick={() => {
                                            setIsEditing(!isEditing);
                                            setEditedText(text);
                                        }}
                                    />
                                    <FaRegTrashAlt
                                        color="white"
                                        onClick={() => openModal("delete")}
                                    />
                                </div>
                            )}
```

2021-09-25 21:11 UTC, sidneyouteiro commented on src/components/Post.js
> +                                }
```
                                onKeyDown={e => {
                                    if(e.key === "Escape") setIsEditing(false)
                                    if(e.key === "Enter") saveModification(e)
                                }}
```

2021-09-25 21:11 UTC, sidneyouteiro commented on src/components/CommentInput.js
> +                    value={!isDisabled && comment}
Depois de uns testes eu vi que enquanto a promise do envio do comentário não voltava o texto que ficava dentro do input era false. Por isso, esse caso é um bom exemplo de quando é valido ter uma string vazia no else do ternário.
`value={!isDisabled ? comment : ""}`

2021-09-26 07:10 UTC, sidneyouteiro approved these changes

2021-09-26 07:10 UTC, merged